### ISSUE TITLE
bug with theme

### ISSUE THREAD

**Issue by skyfall96** [Yavis/hexasbook#1]
Hello, and thanks for your work.
I have installed your theme, it's working, but can't have background images to appear.
chmod is good, i don't understand.
any help?

**Comment by Yavis** [comment]
Hey there,

I will look a little more into it.
I'm not shure when to get to it.
But could you please provide some more information?
Which version of humhub do you use?
What have you tried  so far?
Did you change any of the names/paths and updated the less data? And if you did did you mind to recompile the css files?
Did you try to open the background-image directly via your browser and did that work?

Thanks for following.

**Comment by Yavis** [comment]
> Hello, and thanks for your work.
> I have installed your theme, it's working, but can't have background images to appear.
> chmod is good, i don't understand.
> any help?

Hey there how is it going?
Could not find any issue yet, could you please provide some extra information?
